export const config = {
	RPC_URL: 'http://api.alphanet.rebus.money:26657',
	REST_URL: 'http://api.alphanet.rebus.money:1317',
	EXPLORER_URL: 'https://www.mintscan.io/juno',
	STAKING_URL: 'https://juno.omniflix.co/stake',
	NETWORK_NAME: 'Rebus',
	NETWORK_TYPE: 'testnet',
	CHAIN_ID: 'reb_6666-1',
	CHAIN_NAME: 'Rebus alphanet',
	COIN_DENOM: 'REBUS',
	COIN_MINIMAL_DENOM: 'arebus',
	COIN_DECIMALS: 18,
	PREFIX: 'rebus',
	COIN_TYPE: 118,
	COINGECKO_ID: 'rebus-network',
	DEFAULT_GAS: 200000,
	GAS_PRICE_STEP_LOW: 0.001,
	GAS_PRICE_STEP_AVERAGE: 0.0025,
	GAS_PRICE_STEP_HIGH: 0.004,
	FEATURES: ['stargate'],
};
